import 'package:equatable/equatable.dart';
import 'school_image.dart';

class SchoolEntity extends Equatable {
  final String? id; // Database UUID generated by backend
  final String schoolId; // User UUID associated with the school
  final String name;
  final String address;
  final String province;
  final String district;
  final String discription; // Backend uses 'discription' spelling
  final String type;
  final String principal;
  final int stCount;
  final int techCount;
  final int labCount;
  final int buildingCount;
  final int comCount;
  final bool isSportSchool;
  final bool isPrimarySchool;
  final bool isPoshkaSchool;
  final double? lat;
  final double? lng;
  final List<SchoolImage> images;

  const SchoolEntity({
    this.id,
    required this.schoolId,
    required this.name,
    required this.address,
    required this.province,
    required this.district,
    required this.discription,
    required this.type,
    required this.principal,
    required this.stCount,
    required this.techCount,
    required this.labCount,
    required this.buildingCount,
    required this.comCount,
    required this.isSportSchool,
    required this.isPrimarySchool,
    required this.isPoshkaSchool,
    this.lat,
    this.lng,
    required this.images,
  });

  // Helper constructor for an empty, uncompleted profile
  factory SchoolEntity.empty(String schoolId) {
    return SchoolEntity(
      id: null,
      schoolId: schoolId,
      name: '',
      address: '',
      province: '',
      district: '',
      discription: '',
      type: 'Primary',
      principal: '',
      stCount: 0,
      techCount: 0,
      labCount: 0,
      buildingCount: 0,
      comCount: 0,
      isSportSchool: false,
      isPrimarySchool: false,
      isPoshkaSchool: false,
      lat: null,
      lng: null,
      images: const [],
    );
  }

  bool get isEmpty => name.trim().isEmpty && address.trim().isEmpty;

  @override
  List<Object?> get props => [
        id,
        schoolId,
        name,
        address,
        province,
        district,
        discription,
        type,
        principal,
        stCount,
        techCount,
        labCount,
        buildingCount,
        comCount,
        isSportSchool,
        isPrimarySchool,
        isPoshkaSchool,
        lat,
        lng,
        images,
      ];
}
